### ISSUE TITLE
Why do I have two pet sections, but also some pets not getting in the right place.

### ISSUE THREAD

**Issue by strickland** [lownignitus/AdiBags_Battle_Pet_Items#1]
Crazy to me that I got two battle pet sections, although one called battle pets, the other called battle pet items, but still Pets are not going inside the pet section clearly can see from the screenshot?

https://imgur.com/a/aXe7hcd

I'm asking why not all of them together in one location, pets + pet items, together.

**Comment by lownignitus** [comment]
Have to do with how adibags works and sorts things. Only items that are in the list will be sorted into a section headed with "Battle Pet Items" That is what my addon does. 

The section listed Battle pets and Miscellaneous are AdiBags defaults and not controlled by my addon. 

But that happens because most caged pets dont report properly as Pets and only as an item "Caged pet". you can adjust this by changing the sorting settings for the Miscellaneous section.
